name: Build Game

on: 
  push:
    branches: dev
  pull_request:
    branches: dev
  workflow_dispatch: {}

jobs:
  build:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build Game
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildName: ${{ env.GAME_NAME }}

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
      
  push:
    name: Push Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: ${{ github.workspace }}/build

      - name: Clone Destination Repository
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/${{ env.GH_USER_NAME }}/${{ env.GH_BUILD_REPO_NAME }}.git

      - name: Set Commit Name to Environment Variable
        run: echo "COMMIT_NAME=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
      
      - name: Push Artifacts to Destination Repository
        run: |
          cd ${{ env.GH_BUILD_REPO_NAME }}
          git config user.email "${{ secrets.EMAIL }}"
          git config user.name "${{ env.GH_USER_NAME }}"
          git checkout -B ${{ env.GH_BUILD_BRANCH_NAME }}
          cp -r ${{ github.workspace }}/build/StandaloneWindows/* .
          git add .
          git commit -m "${{ env.COMMIT_NAME }}"
          git push -f origin ${{ env.GH_BUILD_BRANCH_NAME }}